### ISSUE TITLE
Revisar Manual de Usuario.

### ISSUE THREAD

**Issue by denmoujalli** [GuillermoSH/proyecto-daw-ets#14]
#11 
Se ha encontrado luego de haber revisado la documentación que el manual de usuario debe de revisarse y modificarse, ya que solo muestra de que se trata el manual de usuario y no es el manual como tal del software.

**Comment by GuillermoSH** [comment]
Se ha hecho una introducción al manual de usuario y corregido lo que faltaba en el mismo
